"""add entity and note tables

Revision ID: 9d07cdf4a960
Revises: c78dc9644f80
Create Date: 2026-02-26 03:39:41.385569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d07cdf4a960'
down_revision: Union[str, None] = 'c78dc9644f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], name=op.f('fk_entity_paper_id_paper'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity'))
    )
    op.create_index(op.f('ix_entity_paper_id'), 'entity', ['paper_id'], unique=False)
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], name=op.f('fk_note_paper_id_paper'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note'))
    )
    op.create_index(op.f('ix_note_paper_id'), 'note', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_paper_id'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_entity_paper_id'), table_name='entity')
    op.drop_table('entity')
    # ### end Alembic commands ###
