"""add user.papers relationship

Revision ID: c78dc9644f80
Revises: 6bcd4f0d0d67
Create Date: 2026-02-26 01:32:00.410301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78dc9644f80'
down_revision: Union[str, None] = '6bcd4f0d0d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
